### ISSUE TITLE
pip installs develop branch?

### ISSUE THREAD

**Issue by igncampa** [Frojd/wagtail-geo-widget#115]
couldn't follow the docs after installation because `wagtailgeowidget.panels` was raising an error. did a bit of research and it seems to me that pip installs the `develop` branch which uses `wagtailgeowidgets.edit_handlers`.

this seems confusing to me, is this intentional?

**Comment by marteinn** [comment]
Hi @igncampa! The documentation are currently mismatched with the latest PIP version due to a accidental merge to the main branch. These docs should match the PIP version: https://github.com/Frojd/wagtail-geo-widget/tree/d5fa15e3c44be2c047e6721904d0d82e4ffb4251/docs

This issue will be resolved with the next release, I'm keeping this issue open until then.

**Comment by marteinn** [comment]
Documentation are again up to date with the latest PIP release (https://github.com/Frojd/wagtail-geo-widget/releases/tag/v7.0.0). I have also added a contribution guide to avoid this issue in the future. Closing.
