### ISSUE TITLE
Compatibility with new React Streamfield

### ISSUE THREAD

**Issue by rafaponieman** [Frojd/wagtail-geo-widget#33]
Development is close to complete on the new react powered streamfield, and it's currently not compatible with the Geo Widget implementation.

I've reported the issue on wagtail-react-streamfield but there is a need for fixes on the wagtail-geo-widget.

More info over here: https://github.com/noripyt/wagtail-react-streamfield/issues/4

Thank you!!

**Comment by marteinn** [comment]
Thank for the issue @afaponieman! We will definitely make sure this library works with the new stream field, but will probably take a couple of weeks until we have the time to look into it. PR:s is of course much appreciated :)

**Comment by marteinn** [comment]
A small update, I have added partial support for [wagtail-react-streamfield](https://github.com/wagtail/wagtail-react-streamfield) (https://github.com/Frojd/wagtail-geo-widget/commit/b87d0859995d50a8313e8c4a763e3efc82556001). 

The issue now is that the `address_field` is not working and due to how wagtail-react-streamfield works I might need to rethink the GeoBlock structure. I'm starting to work on it now.

**Comment by marteinn** [comment]
There we go, address_field is now supported again (https://github.com/Frojd/wagtail-geo-widget/releases/tag/v5.0.0). Please try it out and let me know if you find any bugs :)
