### ISSUE TITLE
Can wagtail-geo-widget support more complex geometry?

### ISSUE THREAD

**Issue by coredumperror** [Frojd/wagtail-geo-widget#38]
I'm writing a replacement for the map tool my university uses, since we're moving from Drupal to Wagtail, and we need to be able to draw complex polygons, including those with holes in them, for individual buildings. Can this widget, perhaps with heavy modifications by myself, be made to store and display such data? Or do you think I'd have to start entirely from scratch?

If I can build on top of this project to accomplish my goals, I'd be happy to offer my changes as a PR. However, we use purely GeoJSON for our existing map data, so I don't think we'll be using any of the GIS or GeoDjango stuff that's already in place in this library.

**Comment by marteinn** [comment]
Hi @coredumperror!

Very interesting challenge. I think your use case is outside the scope of this project, I would probably start fresh. The reason is that this project basically only allows you to mark one geo location and going beyond this would require some serious changes, especially when you do not need the gis stuff :)

But I think use case is very interesting so please keep me updated on your progress or if theres anything I can help you with!

**Comment by coredumperror** [comment]
I was able to use the knowledge I gained by studying wagtail-geo-widget's code to successfully port my old Drupal-based code to work in Wagtail. So thanks a lot for that!

I'm not certain if my code will ever see the light of day, though, as I ended up needing to couple it fairly closely with the design of our Landmark model. I'd have to make a number of significant changes to genericise the functionality for public use, and I just don't have time right now.
