### ISSUE TITLE
Admin Configurable Settings.

### ISSUE THREAD

**Issue by uroybd** [Frojd/wagtail-geo-widget#56]
In CMS, we expect to configure less from the developer's end.
Instead of setting the variables in the settings, let's put this in a settings model so that the user can change them without developers getting involved.

**Comment by marteinn** [comment]
Hi @uroybd and thanks for the suggestion! This is not a use case I have stumbled upon yet (since I always try to keep these kind of configuration away from site admins), but I see your point. Especially when it comes to multi sites that could have different google map keys.

My idea is to start with adding an abstraction on top of our env value retrieval, that abstraction can then be switched out if one wishes to retrieve values from anything else then settings. Will try to look at it the upcoming weeks.

**Comment by marteinn** [comment]
This is now possible by defining a custom callback for loading google maps api key. This is done in the `GOOGLE_MAPS_V3_APIKEY_CALLBACK` setting.

More info about the setting: https://github.com/Frojd/wagtail-geo-widget/blob/develop/docs/settings.md
And a implementation example: https://github.com/Frojd/wagtail-geo-widget/blob/develop/docs/faq.md#how-can-i-make-the-google-maps-api-key-editable-in-the-admin

This feature is added in https://github.com/Frojd/wagtail-geo-widget/commit/43613d09452185bf9f8775c2bd66f1583938eed1 and will be included in the next 5.3.0 release.

**Comment by marteinn** [comment]
Update: 5.3.0 is now released. If you experience any issue related to this let me know.
