### ISSUE TITLE
Will this awesome widget have template rendering?

### ISSUE THREAD

**Issue by itekhi** [Frojd/wagtail-geo-widget#90]
Thank you for making this widget, it replaced me whole lot of other half-working options. But I did not find a way how to render map inside template, for now I have a custom inclusion tag to render the map.

Could you please make a `wagtailgeowidget_tags` or something?

**Comment by marteinn** [comment]
Hi @itekhi and thank you for the kind words! 

When it comes to template rendering, it is not included in this library. It was removed from our roadmap around 2019 because:
- Maintaining a more rich map falls outside the scope of this library, that has the goal to provide a good editing experience for admin users. [Ref](https://github.com/Frojd/wagtail-geo-widget/pull/21#issuecomment-360997563)
- We don't use regular Wagtail templating, so building a template rendered map would mean that we would have to put a large amount of time into building something we would not use. [Ref](https://github.com/Frojd/wagtail-geo-widget/issues/7#issuecomment-484943567)

As a reference for implementing a custom map I recommend looking at our examples, they show you how to extract values from the data models in templates: https://github.com/Frojd/wagtail-geo-widget/tree/main/example

Hope this explains our reasoning and why I'm closing this issue.
